# Generated by Django 4.2.1 on 2023-05-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(max_length=500)),
                ('last_name_client', models.CharField(max_length=500)),
                ('email_client', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=800)),
                ('sell_price_product', models.FloatField()),
                ('buy_price_product', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('name_supplier', models.CharField(max_length=500)),
                ('phone_supplier', models.CharField(max_length=500)),
                ('email_supplier', models.CharField(max_length=500)),
            ],
        ),
    ]
